### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Dawsson**
duiscoird fixed!

### CODE REVIEW

**Review by UwUAroze — CHANGES_REQUESTED** [review]
you silly head
make it @aroze

**Comment by Dawsson** [comment]
im not ur sl;ave boi idk how

**Comment by UwUAroze** [comment]
go to ur fgorkl
make commit ther

**Comment by Dawsson** [comment]
what fork

**Comment by UwUAroze** [comment]
[THIS ONE?](https://github.com/Dawsson/UwUAroze/tree/patch-1)?!?!?!

**Comment by Dawsson** [comment]
ok now what???

**Comment by Dawsson** [comment]
OK NOW WHAT??

**Comment by Dawsson** [comment]
sorrty I didnt mean to close
agaiun

**Comment by UwUAroze** [comment]
FINALLY

**Review by UwUAroze — APPROVED** [review]
2/10

finally got there, had to be spoonfed like A LITTLE BABY THOUGH

**Comment by Dawsson** [comment]
wow thank toyu SOOOOOOO much

**Pull request merged**
